routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::post('/webhooks/inbound', 'WhatsappController@incoming');

Route::get('/', function () {
    return view('login');
})->name('home');
Auth::routes();
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('mlogin', 'Auth\LoginController@login')->name('mlogin');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

Route::group(['prefix' => 'messages'], function () {
    Route::get('/', ['as' => 'messages', 'uses' => 'MessagesController@index']);
    Route::get('create', ['as' => 'messages.create', 'uses' => 'MessagesController@create']);
    Route::get('create/{client_id}/{process_id}/{step_id}', ['as' => 'messages.client', 'uses' => 'MessagesController@client_create']);
    Route::get('create/{client_id}/{related_party_id}', ['as' => 'messages.relatedparty', 'uses' => 'MessagesController@relatedparty_create']);
    Route::post('/', ['as' => 'messages.store', 'uses' => 'MessagesController@store']);
    Route::get('{id}', ['as' => 'messages.show', 'uses' => 'MessagesController@show']);
    Route::put('{id}', ['as' => 'messages.update', 'uses' => 'MessagesController@update']);
});

Route::get('powerpoint', 'ReportController@powerpoint')->name('powerpoint');

// Registration Routes...
Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
Route::post('register', 'Auth\RegisterController@register');

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');

Route::get('profile/{user?}', 'UserController@profile')->name('profile');
Route::get('settings', 'UserController@settings')->name('settings');
Route::post('settings/password', 'UserController@handlePassword')->name('settings.password');
Route::post('settings/profile', 'UserController@handleProfile')->name('settings.profile');
Route::post('settings/notifications', 'UserController@handleNotifications')->name('settings.notifications');

Route::any('/', 'HomeController@index')->name('home');
Route::any('/home', 'HomeController@index');
Route::get('recents', 'HomeController@recents')->name('recents');
Route::any('dashboard', 'HomeController@dashboard')->name('dashboard');
Route::any('progress', 'HomeController@progress')->name('progress');
Route::get('calendar', 'HomeController@calendar')->name('calendar');
Route::get('help', 'HelpController@create')->name('help.create');
Route::post('help', 'HelpController@store')->name('help.store');

Route::resource('emaillogs', 'EmailLogsController');
Route::get('emaillogs/{email_id}', 'EmailLogsController@show')->name('emaillogs.show');

/*Route::get('storage/crf', 'AssetController@getCrf')->name('crf_client');*/
Route::get('storage/avatar', 'AssetController@getAvatar')->name('avatar');
Route::get('storage/document', 'AssetController@getDocument')->name('document');
Route::get('storage/template', 'AssetController@getTemplate')->name('template');

Route::get('clients/amlreviewed', 'ClientController@amlReviewed')->name('clients.amlreviewed');
Route::get('clients/amlapproved', 'ClientController@amlApproved')->name('clients.amlapproved');
Route::get('clients/amlreviewedandapproved', 'ClientController@amlReviewedAndApproved')->name('clients.amlreviewedandapproved');
Route::get('clients/completed/{step_id}', 'ClientController@completed')->name('clients.completed');

Route::get('clients/xlsexport','ClientController@xlsExport')->name('clients.xlsexport');
Route::resource('clients', 'ClientController');

Route::any('clients/create','ClientController@create')->name('clients.create');
Route::post('clients/{client}/updates','ClientController@update')->name('clients.savedetail');
Route::get('clients/{client}/avatar','ClientController@generateAvatar')->name('clients.avatar');
Route::get('clients/{client}/progress','ClientController@progress')->name('clients.progress');
Route::get('clients/{client}/processes/{process}/{step}','ClientController@processes')->name('clients.processes');
Route::post('clients/{client}/progress','ClientController@storeProgress')->name('clients.storeprogress');
Route::post('clients/{client}/actions','ClientController@storeActions')->name('clients.storeactions');
Route::post('clients/{client}/progress/{process?}/{step?}','ClientController@completeStep')->name('clients.completestep');
Route::post('clients/{client}/progress2/{process?}/{step?}','ClientController@completeStep2')->name('clients.completestep2');
Route::get('clients/{client}/progress/{process}/{step}','ClientController@stepProgress')->name('clients.stepprogress');
Route::get('clients/{client}/calculators/{process}/{step}','ClientController@calculators')->name('clients.calculators');
Route::get('clients/{client}/progressaction/{process}/{step}/{action_id}','ClientController@stepProgressAction')->name('clients.stepprogressaction');
Route::get('clients/{client}/documents/{process}/{step}','ClientController@documents')->name('clients.documents');
Route::get('clients/{client}/forms/{process}/{step}','ClientController@forms')->name('clients.forms');
Route::get('clients/{client}/edit/{process}/{step}','ClientController@edit')->name('clients.edit');
Route::get('clients/{client}/forms/uploadform','ClientController@uploadforms')->name('forms.uploadforms');
Route::get('clients/{client}/forms/editform/{formid}','ClientController@edituploadforms')->name('forms.editforms');
Route::post('clients/{client}/forms/storeform','ClientController@storeuploadforms')->name('forms.uploadstore');
Route::post('clients/{clientid}/forms/{formid}/formupdate','ClientController@updateuploadforms')->name('forms.formupdate');
Route::get('clients/{client}/forms/createcrf','ClientController@createCrfForm')->name('forms.createcrf');
Route::get('clients/{client}/forms/editcrf/{formid}','ClientController@editCrfForm')->name('forms.editcrf');
Route::get('clients/{client}/forms/signcrf/{formid}','ClientController@signCrfForm')->name('forms.signcrf');
Route::post('clients/{clientid}/forms/{formid}/updatecrf','ClientController@updateCrfForm')->name('forms.updatecrf');
Route::post('clients/{client}/forms/storecrf','ClientController@saveCrfForm')->name('forms.storecrf');
Route::get('clients/{client}/forms/{formid}/generatecrf','ClientController@generateCrfForm')->name('forms.generatecrf');
Route::get('clients/{client}/forms/upload','ClientController@saveCrfForm')->name('forms.upload');
Route::get('clients/{client}/forms/delete/{formid}','ClientController@deleteCrfForm')->name('crfforms.destroy');
Route::get('clients/{client_id}/completed/{step_id}/{newdate}','ClientController@complete')->name('clients.complete');
Route::get('clients/{client_id}/uncompleted/{step_id}','ClientController@uncomplete')->name('clients.uncomplete');
Route::get('clients/{client_id}/changecompleted/{step_id}/{newdate}','ClientController@changecomplete')->name('clients.changecomplete');
Route::post('clients/{client}/sendnotification/{activity?}','ClientController@sendNotification')->name('clients.sendnotification');
Route::post('clients/{client}/sendtemplate/{activity?}','ClientController@sendTemplate')->name('clients.sendtemplate');
Route::post('clients/{client}/senddocument/{activity?}','ClientController@sendDocument')->name('clients.senddocument');
Route::get('clients/{client}/viewtemplate/{template?}','ClientController@viewTemplate')->name('clients.viewtemplate');
Route::get('clients/{client}/viewdocument/{document?}','ClientController@viewDocument')->name('clients.viewdocument');
/*Route::put('clients/{client}/follow','ClientController@follow')->name('clients.follow');*/
Route::get('clients/{client}/activityprogress/{process}/{step}','ClientController@activityProgress')->name('clients.activityprogress');
Route::get('clients/{client}/getcomments','ClientController@getComment')->name('clients.getcomment');
Route::post('clients/{client}/storecomment','ClientController@storeComment')->name('clients.storecomment');
Route::post('clients/deleteclientcomment/{comment}','ClientController@deleteComment')->name('clients.deletecomment');
Route::post('clients/{client}/progressing','ClientController@storeProgressing')->name('clients.progressing');
/*Route::post('clients/{client}/qa','ClientController@storeQA')->name('clients.qa');*/
/*Route::post('clients/{client}/qacomplete','ClientController@completeQA')->name('clients.qacomplete');
Route::post('clients/{client}/qaprod','ClientController@storeProd')->name('clients.qaprod');*/
Route::post('clients/{client}/approval','ClientController@approval')->name('clients.approval');
Route::post('clients/{client}/senddocuments/{activity?}','ClientController@sendDocuments')->name('clients.senddocuments');

Route::post('clients/{client}/sendmail','ClientController@sendMail')->name('clients.sendMail');
Route::post('clients/{client}/sendwhatsapp','ClientController@sendWhatsapp')->name('clients.sendWhatsapp');

Route::post('voice/record/{card}','TaskController@recordVoice')->name('tasks.voicerecord');

Route::get('clients/{clientid}/overview/{process}/{step}','ClientController@overview')->name('clients.overview');
Route::get('clients/{clientid}/details/{process}/{step}','ClientController@details')->name('clients.details');
Route::get('clients/{client}/delete','ClientController@destroy')->name('clients.delete');

resources/views/calendar.blade.php
@extends('layouts.app')

@section('title') Calendar @endsection

@section('header')
    <h1><i class="fa fa-calendar-o"></i> @yield('title')</h1>
@endsection

@section('content')
    <form class="form-inline mt-3">
        Show &nbsp;
        {{Form::select('s',['all'=>'All','mine'=>'My','company'=>'Branch'],old('selection'),['class'=>'form-control form-control-sm'])}}
        &nbsp; from &nbsp;
        {{Form::select('s',['all'=>'All Time','mine'=>'My','company'=>'Branch'],old('selection'),['class'=>'form-control form-control-sm'])}}
        &nbsp; matching &nbsp;
        <div class="input-group input-group-sm">
            <div class="input-group-prepend">
                <span class="input-group-text"><i class="fa fa-search"></i></span>
            </div>
            {{Form::text('q',old('query'),['class'=>'form-control','placeholder'=>'Search...'])}}
        </div>
    </form>

    <hr>

    <div id="calendar">
    </div>
@endsection

@section('extra-css')
    <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.9.0/fullcalendar.min.css'/>
@endsection

@section('extra-js')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.20.1/moment.min.js"></script>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.9.0/fullcalendar.min.js'></script>
    <script>
        $(document).ready(function() {
            $('#calendar').fullCalendar({
                header: {
                    left: 'prev,next today',
                    center: 'title',
                    right: 'listDay,month,agendaWeek,agendaDay'
                },eventSources: [

    // your event source
    {
      events: [ // put the array in the `events` property
        {
          title  : 'event1',
          start  : '2018-04-01'
        },
        {
          title  : 'event2',
          start  : '2018-04-05',
          end    : '2018-04-07'
        },
        {
          title  : 'event3',
          start  : '2018-04-09T12:30:00',
        }
      ],
      color: 'black',     // an option!
      textColor: 'yellow' // an option!
    }

    // any other event sources...

  ]

            })

        });
    </script>
@endsection

resources/views/dashboard.blade.php
@extends('flow.default')

@section('title') Dashboard @endsection

@section('header')
    <div class="container-fluid container-title">
        <h3>@yield('title')</h3>
        <div style="float: right;">
            <form method="get" class="form-inline mt-0">
                {{Form::label('Process:')}}&nbsp;&nbsp;
                {{Form::select('p',$processes,old('p'),['class'=>'form-control form-control-sm','placeholder'=>'Please select','id'=>'dashboard_process'])}}&nbsp;&nbsp;
                <button type="submit" class="btn btn-sm btn-secondary ml-2 mr-2"><i class="fa fa-search"></i> Search</button>
            </form>
        </div>
    </div>
@endsection

@section('content')
    <div class="content-container page-content">
        <div class="row col-md-12 h-100">
            <div class="container-fluid container-title">
                <h3>@yield('title')</h3>
            </div>
            <div class="container-fluid container-content dashboard" style="overflow: hidden;">
                <div class="row mt-3 dashboard-region">
                @for($i = 0;$i < count($regions);$i++)

                    <!-- Close the row off and start a new one for every 4 regions -->
                        @if($i == 4)

                        </div>
                        <div class="row mt-3 dashboard-region">
                            <div class="col-lg col-md-6">

                        @else
                            <div class="col-lg col-md-6">

                        @endif

                                <div class="card text-white {{--@php echo $style[$i] @endphp--}} blackboard-region" style="background:{{(isset($regions[$i]['colour']) ? $regions[$i]['colour'] : '')}}">
                                    <div class="card-body" style="padding: 0.75rem;">
                                        @php $id = $regions[$i]['id'] @endphp
                                        <h4><i class="fa fa-chart-line"></i> {{(!empty($client_step_counts[$id]) ? $client_step_counts[$id] : '0')}}</h4>
                                        <p class="d-inline-block">{{$regions[$i]["name"]}}</p>
                                        @if($regions[$i]['id'] == '5')
                                            <span class="float-right d-inline-block"><a href="{{route('clients.index',['p'=>$regions[$i]['process_id'],'step'=>$regions[$i]['id']])}}&c=no" class="btn btn-sm btn-outline-light"><i class="fa fa-share"></i> View</a></span>
                                        @else
                                            <span class="float-right d-inline-block"><a href="{{route('clients.index',['p'=>$regions[$i]['process_id'],'step'=>$regions[$i]['id']])}}&c=all" class="btn btn-sm btn-outline-light"><i class="fa fa-share"></i> View</a></span>
                                        @endif

                                    </div>
                                </div>
                            </div>


                @endfor
                    @if($client_converted_count != '-1')
                        <div class="col-lg col-md-6">
                            <div class="card text-white completed-region blackboard-region">
                                <div class="card-body" style="padding: 0.75rem;">

                                    <h4><i class="fa fa-chart-line"></i> {{(!empty($client_converted_count) ? $client_converted_count : '0')}}</h4>
                                    <p class="d-inline-block">Completed</p>
                                    @if($config->show_converted_currency_total != null && $config->show_converted_currency_total == '1')
                                        <p class="d-inline-block">{{$converted_value}}</p>
                                    @endif
                                    <span class="float-right d-inline-block"><a href="{{route('clients.index',['step'=>1000])}}&p={{$process_id}}&f=2019-01-01&t=2019-12-31" class="btn btn-sm btn-outline-light"><i class="fa fa-share"></i> View</a></span>
                                </div>
                            </div>
                        </div>
                    @endif
                </div>

                    <div class="row pt-3">
                        <div class="col-lg-6">
                            <div class="card">
                                <div class="card-header">
                                    Converted Clients
                                </div>
                                <div class="card-body p-1 pt-2 pb-2">
                                    <div id="blackboard-dashboard-1" class="m-0" style="max-height: 250px"></div>
                                </div>
                            </div>
                        </div>

                        <div class="col-lg-6">
                            <div class="card">
                                <div class="card-header">
                                    Outstanding Activities for {{$outstanding_activity_name}}
                                </div>
                                <div class="card-body p-1 pt-2 pb-2">
                                    <div id="blackboard-dashboard-2" class="m-0" style="max-height: 250px"></div>
                                </div>
                            </div>
                        </div>
                    </div>
            </div>
        </div>
    </div>

@endsection
@section('extra-js')
    <script>

        $(document).ready(function() {
            $('#dashboard_process').on('change',function (){
                this.form.submit();
            });

            Highcharts.theme = {
                colors: ['#86bffd', '#17a2b8'],
                title: {
                    text: ''
                },
                chart: {
                    type: 'column',
                    height: '250px'
                },
                yAxis: {
                    min: 0,
                    title: {
                        text: ''
                    }
                },
                xAxis: {
                    crosshair: true
                },
                credits: {
                    enabled: false
                },
                    legend: {
                    enabled: false
                },
            };

            Highcharts.setOptions(Highcharts.theme);


            let blackboardDashboard1 = Highcharts.chart('blackboard-dashboard-1', {
                yAxis: {
                    labels: {
                        formatter: function (x) {
                            return (this.value) + " clients";
                        }
                    },
                    plotLines: [{
                        color: '#dc3545',
                        width: 2,
                        value: @if($config->onboards_per_day) {{$config->onboards_per_day}} @else '' @endif,
                        dashStyle: 'shortdash',
                        zIndex: 5
                    }]
                },
                xAxis: {
                    categories: [
                        @foreach($client_onboards as $key => $client)
                            '{{$key}}',
                        @endforeach
                    ]
                },
                tooltip: {
                    formatter: function () {
                        return '<small class="text-muted">' + this.x + '</small><br><b>' + this.y + ' clients</b>';
                    }
                },
                series: [{
                    data: [

                            @foreach($client_onboards as $client)
                            @if($client > 0)
                            {{$client}},
                            @endif
                            @endforeach

                    ]
                }],
                plotOptions: {
                    series: {
                        cursor: 'pointer',
                        borderRadiusTopLeft: '3px',
                        borderRadiusTopRight: '3px',
                        point: {
                            events: {
                                click: function () {
                                    let start = '';
                                    switch ('{{request()->input('r')}}') {
                                        case 'day':
                                            start = moment(this.category, 'DD MMMM YYYY');
                                            location.href = '{!! route('clients.index',['l'=>request()->input('l'),'p'=>request()->input('p'),'c'=>'yes']) !!}&f=' + start.format('YYYY-MM-DD') + '&t=' + start.format('YYYY-MM-DD');
                                            break;
                                        case 'week':
                                            start = moment(moment(this.category).format('WW YYYY'), 'WW YYYY');
                                            location.href = '{!! route('clients.index',['l'=>request()->input('l'),'p'=>request()->input('p'),'c'=>'yes']) !!}&f=' + start.format('YYYY-MM-DD') + '&t=' + start.add(6, 'days').format('YYYY-MM-DD');
                                            break;
                                        case 'month':
                                            start = moment(this.category, 'MMMM YYYY');
                                            location.href = '{!! route('clients.index',['l'=>request()->input('l'),'p'=>request()->input('p'),'c'=>'yes']) !!}&f=' + start.format('YYYY-MM-DD') + '&t=' + start.add(1, 'months').format('YYYY-MM-DD');
                                            break;
                                        case 'year':
                                            start = moment(this.category, 'YYYY');
                                            location.href = '{!! route('clients.index',['l'=>request()->input('l'),'p'=>request()->input('p'),'c'=>'yes']) !!}&f=' + start.format('YYYY-MM-DD') + '&t=' + start.add(1, 'years').format('YYYY-MM-DD');
                                            break;
                                    }
                                }
                            }
                        }
                    }
                },
                chart: {
                    type: 'column',
                    height: '250px'
                },
            });

            let blackboardDashboard2 = Highcharts.chart('blackboard-dashboard-2', {
                yAxis: [
                    {
                        title: {},
                        style: {
                            color: Highcharts.getOptions().colors[0]
                        }
                    },
                    {
                        title: {},
                        style: {
                            color: Highcharts.getOptions().colors[1]
                        },
                        opposite: true
                    }
                ],
                xAxis: {
                    categories: [
                        @foreach($process_outstanding_activities as $name => $amount)
                            '{{$name}}',
                        @endforeach
                    ]
                },
                series: [
                    {
                        name: 'Outstanding Activities',
                        data: [
                            @foreach($process_outstanding_activities as $amount)
                            @if($amount['user'] > 0)
                            {{$amount['user']}},
                            @endif
                            @endforeach
                        ]
                    },
                ],
                tooltip: {
                    shared: true
                },
                plotOptions: {
                    series: {
                        cursor: 'pointer',
                        borderRadiusTopLeft: '3px',
                        borderRadiusTopRight: '3px',
                        point: {
                            events: {
                                click: function () {
                                    location.href = '{!! route('clients.index',['l'=>request()->input('l'),'p'=>request()->input('p')]) !!}&oa='+this.category+'&s=all&c=all&step={!! $outstanding_step_id !!}';
                                }
                            }
                        }
                    }
                }
            });
        })

    </script>
@endsection

resources/views/insight.blade.php
@extends('adminlte.default')

@section('title') Insight @endsection

@section('header')
    <div class="container-fluid container-title">
        <h3>@yield('title')</h3>
    </div>
@endsection

@section('content')
    <div class="container-fluid">
    <blackboard-insight add-user-link="{{route('clients.create')}}"></blackboard-insight>
    </div>
@endsection

resources/views/recents.blade.php
@extends('flow.default')

@section('title') Recents @endsection

@section('content')
    <div class="content-container page-content">
        <div class="row col-md-12 h-100">
            <div class="container-fluid container-title">
                <h3>@yield('title')</h3>
            </div>
            <div class="container-fluid container-content">
                <div class="table-responsive ">
                    <table class="table table-sm table-bordered blackboard-recents">
                        <thead>
                        <tr>
                            <th colspan="3">
                                Recent Applications
                                <a href="{{route('clients.index')}}" class="btn btn-primary btn-sm float-right"><i class="fa fa-eye"></i> View all</a>
                            </th>
                        </tr>
                        <tr>
                            <th>
                                Client
                            </th>
                            <th>
                                Application
                            </th>
                            <th class="last">

                            </th>
                        </tr>
                        </thead>
                        @forelse($clients as $client)
                            <tr>
                                <td>
                                    <a href="{{route('clients.show',[$client->client_id,$client->process_id,$client->step_id])}}">{{($client->first_name)}} {{($client->last_name)}}</a>
                                </td>
                                <td>
                                    <a href="{{route('clients.show',[$client->client_id,$client->process_id,$client->step_id])}}">{{$client->process->name}}</a>
                                </td>
                                <td class="last">
                                    <span class="float-right text-muted"><small><i class="fa fa-calendar"></i> {{$client->updated_at}}</small></span>
                                </td>
                            </tr>
                        @empty
                            <tr>
                                <td colspan="3">No recent applications</td>
                            </tr>
                        @endforelse
                    </table>
        </div>
            </div>
        </div>
    </div>
@endsection